# Generated by Django 3.2.6 on 2021-09-02 09:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('logserver', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitbox',
            name='last_log',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
