# Generated by Django 4.0.2 on 2022-03-21 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logserver', '0002_kitbox_last_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='MQTTDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modem_id', models.IntegerField()),
                ('add_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
