# Generated by Django 4.0.2 on 2022-03-22 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logserver', '0003_mqttdevice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[(0, 'Нет событий'), (1, 'Включение'), (2, 'Модем активирован'), (3, 'Модем деактивирован'), (4, 'Продажа')], default=0, max_length=5)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device', to='logserver.mqttdevice')),
            ],
        ),
    ]
