# Generated by Django 4.0.2 on 2023-09-05 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logserver', '0005_event_payload'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kitbox',
            old_name='last_ping',
            new_name='add_at',
        ),
        migrations.RemoveField(
            model_name='kitbox',
            name='last_log',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='MQTTDevice',
        ),
    ]
